### ISSUE TITLE
Error when running pysam count_coverage

### ISSUE THREAD

**Issue by ccedmendoza** [ARTbio/tools-artbio#145]
I get the following error when running mircounts.py from commit 3d85754193e455a80d7ca18e84d3dd7e77b64cc2 with the command ::
python ~/tools-artbio/tools/mircounts/mircounts.py --alignment test-data/clipped.out.bam --gff test-data/translated_dme.gff3 -p --lattice lattice_out --pre_mirs_output output_pre_mirs_count.tab

Traceback (most recent call last):
  File "/home/cedric/tools-artbio/tools/mircounts/mircounts.py", line 133, in <module>
    if __main__():
  File "/home/cedric/tools-artbio/tools/mircounts/mircounts.py", line 123, in __main__
    pre_mirs = get_pre_mir_counts(bamfile)
  File "/home/cedric/tools-artbio/tools/mircounts/mircounts.py", line 36, in get_pre_mir_counts
    bamfile.count_coverage(ref)]
  File "pysam/libcalignmentfile.pyx", line 1225, in pysam.libcalignmentfile.AlignmentFile.count_coverage (pysam/libcalignmentfile.c:13740)
TypeError: an integer is required

**Comment by ccedmendoza** [comment]
found the cause of the problem inn here https://github.com/pysam-developers/pysam/issues/302
aparently if start and end are not set in count_coverage it will raise that error
